### ISSUE TITLE
Need to be able to set our own operators

### ISSUE THREAD

**Issue by hailwood** [railken/search-query#6]
E,g, when using `new Resolvers\EwResolver(),` it would be great if we could do `new Resolvers\EwResolver('ends_with'),` which would set the regex to look for `ends_with` rather than `ew` as the operator.

**Comment by railken** [comment]
Thanks for the suggestion!

Currently, for each resolver there are at least 2 operators (one with symbols and one with letters), for e.g. [EqResolver](https://github.com/railken/search-query/blob/master/src/Languages/BoomTree/Resolvers/EqResolver.php) can have both ```eq``` and ```=```.

So, in order to change these operators through the costructor, an array is expected. The result should be something like this: ```new Resolvers\EqResolver(['eq', '=', 'equals', 'custom'])```, in your case ```new Resolvers\EwResolver(['ew', 'ends_with', '$='])```. 

You have expressed the will to overwrite the current operators, but if someone wants to "add" and not "overwrite" ? You will have to repeat the default operators.

Also, having a list of Resolvers full of different arrays is kind of ugly, but maybe it just me. 

Ultimately you can already change the operators by extending the resolvers and creating your own language.

 I'll think more about it later

**Comment by hailwood** [comment]
Fair call, 

I didn't research this enough before proposing this suggestion, you're correct that it's trivial to create your own due to the actual node being separate from the resolver.
